 let result;
      try {
        result = lab.runLab(3);
      } catch {
        result = "Error thrown";
      }